% Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
% By considering the terms in the Fibonacci sequence whose values do not exceed the input value, find the sum of the even-valued terms.

function y = euler002(x)
    y = 0;
    previousNumber = 1;
    fibonacciNumber = 1;
    while fibonacciNumber <= x
        if mod(fibonacciNumber,2) == 0
           y = y + fibonacciNumber;
        end
        [fibonacciNumber, previousNumber] = fibonacci(previousNumber, fibonacciNumber);
    end
end


function [y, x1] = fibonacci(x1, x2)
    y = x1 + x2;
    x1 = x2;
end